import "./globals.css";
import { Inter } from "next/font/google";
import MyFooter from "@/components/layout/MyFooter";
import MyNavbar from "@/components/layout/MyNavbar";
import { MainContextProvider } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainContextProvider>
          <MyNavbar />
          {props.children}
          <MyFooter />
        </MainContextProvider>
      </body>
    </html>
  );
}
